### ISSUE TITLE
Coregistration

### ISSUE THREAD

**Issue by 1tron1** [SIVICLab/sivic#51]
I'm just curious about the process of coregistering spectra and mri images, is there a good place to get started?

**Comment by beckolson** [comment]
SIVIC does not currently provide a coregistration algrothim for spectra and mri, but it does permit the display of spectral grid overlayed on MRI images. Our main community portal is through sourceforge: sivic.sourceforge.net. If you explore our wiki you'll find tutorials with sample data for getting started with SIVIC.
