### ISSUE TITLE
Create updated build wiki.

### ISSUE THREAD

**Issue by jedchan** [SIVICLab/sivic#83]
Hi SIVIC devs. @agentmess. @jccrane and @beckolson 

I couldn't find official build instructions and thought I would  give it try and build it myself outside the confines of UCSF. This took several days, but I managed to build sivic from the older build page instructions on Sourceforge here:

https://sourceforge.net/p/sivic/sivicwiki/svk_installation/

The information here needs updating, but luckily I was able to figure out how to build SIVIC based on the information in the cmake files. I'll post updated build instructions in this issue. If possible, this should be added to the wiki or README.md. I can do a PR if this is preferred.

**Comment by jedchan** [comment]
Instructions - This was Built using CentOS 7.9 ( GCC 4.8.5 / GLIBC 2.17). Build is forward compatible with EL8 and EL9. Make sure to install the minimum required packages to build SIVIC described in this Dockerfile: https://github.com/SIVICLab/sivic/blob/master/docker/centos7/Dockerfile

1. Download the following packages
- https://github.com/InsightSoftwareConsortium/ITK/archive/refs/tags/v4.4.1.tar.gz
- https://gitlab.kitware.com/vtk/vtk/-/archive/v6.3.0/vtk-v6.3.0.tar.gz
- https://github.com/SIVICLab/KWWidgets
- https://dicom.offis.de/download/dcmtk/dcmtk367/dcmtk-3.6.7.tar.gz
- https://sourceforge.net/projects/tcl/files/Tcl/8.5.19/tcl8.5.19-src.tar.gz/download
- https://sourceforge.net/projects/tcl/files/Tcl/8.5.19/tk8.5.19-src.tar.gz/download
- 
2. Build TCL and TK packages (version 8.5.19)
- ../configure --prefix=/usr/local/sivic/build/deps/tcl8.5.19 --enable-shared
- ../configure --with-x --prefix=/usr/local/sivic/build/deps/tk8.5.19 --with-tcl=/usr/local/sivic/build/deps/tcl8.5.19/lib --enable-shared

3. Build DCMTK 3.6.7 (cmake)
- BUILD_SHARED_LIBS=ON
- CMAKE_INSTALL_PREFIX=/usr/local/sivic/build/deps/dcmtk-3.6.7

4. Build ITK 4.4.1 (cmake)
- BUILD_EXAMPLES=OFF
- BUILD_SHARED_LIBS=ON
- BUILD_TESTING=OFF
- CMAKE_INSTALL_PREFIX=/usr/local/sivic/build/deps/ITK-4.4.1

5. Build clapack 3.2.1 (cmake)
- BUILD_TESTING=ON
- CMAKE_INSTALL_PREFIX=/usr/local/sivic/build/deps/clapack-3.2.1
- USE_BLAS_WRAP=ON

6. Build VTK 6.3.0 (cmake)
- BUILD_SHARED_LIBS=ON
- BUILD_TESTING=OFF
- CMAKE_INSTALL_PREFIX=/usr/local/sivic/build/deps/VTK-6.3.0
- VTK_Group_Tk=ON
- VTK_USE_TK=ON
- VTK_TCL_TK_STATIC=ON
- Module_vtkWrappingTcl=ON
- Module_vtkTclTk=ON
- TCL_LIBRARY=/usr/local/sivic/build/deps/tcl8.5.19/lib/libtcl8.5.so
- TCL_TCLSH=/usr/local/sivic/build/deps/tcl8.5.19/bin/tclsh8.5
- TK_INCLUDE_PATH=/usr/local/sivic/build/deps/tk8.5.19/include
- TK_LIBRARY=/usr/local/sivic/build/deps/tk8.5.19/lib/libtk8.5.so

7.  set environment variables for DCMTK_DIR and VTK_DIR
- export DCMTK_DIR=/usr/local/sivic/build/deps/dcmtk-3.6.7
- export VTK_DIR=/usr/local/sivic/build/deps/VTK-6.3.0

9. KWWidgets (cmake) - make sure to perform step 7 first before running cmake
- CMAKE_INSTALL_PREFIX=/usr/local/sivic/build/deps/KWWidgets
- VTK_DIR=/usr/local/sivic/build/deps/VTK-6.3.0/lib/cmake/vtk-6.3
- TCL_INCLUDE_PATH=/usr/local/sivic/build/deps/tcl8.5.19/include
- TCL_LIBRARY=/usr/local/sivic/build/deps/tcl8.5.19/lib/libtcl8.5.so
- TCL_TCLSH=/usr/local/sivic/build/deps/tcl8.5.19/bin/tclsh8.5
- TK_INCLUDE_PATH=/usr/local/sivic/build/deps/tk8.5.19/include
- TK_LIBRARY=/usr/local/sivic/build/deps/tk8.5.19/lib/libtk8.5.so

10. Build SIVIC (cmake)
- BUILD_CLAPACK=ON
- CLAPACK_DIR=/usr/local/sivic/build/deps/clapack-3.2.1/lib
- CMAKE_INSTALL_PREFIX=/usr/local/sivic/sivic
- DCMTK_DIR=/usr/local/sivic/build/deps/dcmtk-3.6.7
- ITK_DIR=/sivic/build/deps/ITK-4.4.1/lib/cmake/ITK-4.4
- KWWidgets_DIR=/usr/local/sivic/build/deps/KWWidgets/lib/KWWidgets
- VTK_DIR/usr/local/sivic/build/deps/VTK-6.3.0/lib/cmake/vtk-6.3

**Comment by jedchan** [comment]
https://github.com/SIVICLab/sivic/commit/16c667454c5ebbf2fa417988e0f3af5e30ea791c#commitcomment-140393442

**Comment by jedchan** [comment]
32bit support has been removed since OSX Mojave so building dependencies  using 32bit compatibility flags will fail.

**Comment by jedchan** [comment]
Command line tools will not build using VTK 6.3.0. 

VTK 5.10.1 will need to be used.

**Comment by jedchan** [comment]
BUILD_APPS needs to be enabled in order to build command line tools. OPENSSL is needed as well.

**Comment by agentmess** [comment]
Now added to README
